GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoibWF5dXJlc2giLCJpYXQiOjE3MjAwMDcyODYsImV4cCI6MTcyMDAwODE4Nn0.Ccup_pCjRgnBbevvzdmt0ET4uuGnF5UTVyn6youRO4Y
### Fetch All Users
GET http://localhost:3000/auth/all

### Add New User
POST http://localhost:3000/auth/adduser
Content-Type: application/json

{
    "username" : "john_doe",
    "email" : "john.doe@example.com",
    "password" : "johndoe"
}


### Login User
POST http://localhost:3000/auth/login 
Content-Type: application/json

{
    "username" : "mayuresh",
    "password" : "mayuresh"
}

### Generate Access Token 
POST http://localhost:3000/auth/refreshtoken
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoibWF5dXJlc2giLCJpYXQiOjE3MjAwMDgwOTYsImV4cCI6MTcyMTMwNDA5Nn0.mZOCEXxrFBqc7sKbP8Ed_QXi6dygqwR4BaAletwAEYo"
}



### Login
POST http://localhost:3000/auth/login    

### Refresh token
POST http://localhost:3000/auth/refresh-token    

### logout
DELETE http://localhost:3000/auth/logout        

###
GET http://localhost:3000/students/all

### 
POST http://localhost:3000/students/newStudent
Content-Type: application/json

{
    "fname": "Mayuresh",
    "lname": "Gavai",
    "phone": "678-412-2345",
    "address": "ABC Cedar Street, Dubai",
    "course": "Computer Engineering",
    "div": "C",
    "acad_year": 2022
}