GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoibWF5dXJlc2giLCJpYXQiOjE3MjAwMTAxNzEsImV4cCI6MTcyMDAxMTA3MX0.DheoSoE81lmCli7EutdmnjwqkyG2HSx5LseUvoGG8TU

### Fetch All Users
GET http://localhost:3000/auth/all

### Add New User
POST http://localhost:3000/auth/adduser
Content-Type: application/json

{
    "username" : "john_doe",
    "email" : "john.doe@example.com",
    "password" : "johndoe"
}


### Login User
POST http://localhost:3000/auth/login 
Content-Type: application/json

{
    "username" : "mayuresh",
    "password" : "mayuresh"
}

### Generate Access Token 
POST http://localhost:3000/auth/refreshtoken
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoibWF5dXJlc2giLCJpYXQiOjE3MjAwMTA4NDIsImV4cCI6MTcyMTMwNjg0Mn0.BHXgxjG2itcsWLmWTcTLjYJm6nMiNAp7RDhrvaTj4WE"
}

### Logout User
DELETE http://localhost:3000/auth/logout        
Content-Type : application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoibWF5dXJlc2giLCJpYXQiOjE3MjAwMTA5NzAsImV4cCI6MTcyMTMwNjk3MH0.GjKaBwXXfNv4ayvjThe4g76CEpylaU6WWlNpiFGu2y8"
}

### Login
POST http://localhost:3000/auth/login    

### Refresh token
POST http://localhost:3000/auth/refresh-token    

### logout
DELETE http://localhost:3000/auth/logout        

###
GET http://localhost:3000/students/all

### 
POST http://localhost:3000/students/newStudent
Content-Type: application/json

{
    "fname": "Mayuresh",
    "lname": "Gavai",
    "phone": "678-412-2345",
    "address": "ABC Cedar Street, Dubai",
    "course": "Computer Engineering",
    "div": "C",
    "acad_year": 2022
}